apiVersion: apps/v1
kind: Deployment
metadata:
  name: argofish-deployment
  labels:
    app: argofish-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: argofish-app
  template:
    metadata:
      labels:
        app: argofish-app
    spec:
      containers:
      - name: argofish-app
        image: kasacka/argofish:2.0
        ports:
        - containerPort: 80